"""Add role field to user model

Revision ID: ecc898d6ac83
Revises: dc597bb4127c
Create Date: 2025-11-12 05:39:43.418175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ecc898d6ac83'
down_revision: Union[str, None] = 'dc597bb4127c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Create ENUM type first
    adminrole_enum = sa.Enum('super_admin', 'editor', 'viewer', name='adminrole')
    adminrole_enum.create(op.get_bind(), checkfirst=True)
    op.add_column('user', sa.Column('role', adminrole_enum, server_default='viewer', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'role')
    # Drop ENUM type after column is removed
    sa.Enum(name='adminrole').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
